name: First_workflow
on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello Goodmorning"
      - name: Print Good bye
        run: echo "Done - bye!"
